version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,opensearch
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-resources:/docker-entrypoint-initaws.d"
    networks:
      - ops-network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    ports:
      - "9200:9200"
      - "9600:9600" 
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - ops-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    networks:
      - ops-network
      
  mcp-server-sse:
    build:
      context: ./ops-agent-backend
      dockerfile: Dockerfile.mcp-server-sse
    ports:
      - "3001:3001"
    environment:
      - AWS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCOUNT_ID=000000000000
      - ENVIRONMENT=nonlive
      - OPENSEARCH_HOST=http://opensearch:9200
      - OPENSEARCH_INDEX_ID=logs
      - OPENSEARCH_DEFAULT_VIEW_ID=default
      - MCP_AGENT_URL=http://host.docker.internal:3001/sse
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
      - FRONTEND_URL=http://host.docker.internal:3000
      - ORDER_TABLE_NAME=billing.Order
    depends_on:
      - localstack
      - opensearch
    volumes:
      - ./ops-agent-backend/.env:/app/.env
      - ./ops-agent-backend/dlqs.json:/app/dlqs.json
    networks:
      - ops-network

  mcp-api-server:
    build:
      context: ./ops-agent-backend
      dockerfile: Dockerfile.mcp-api-server
    ports:
      - "3002:3002"
    environment:
      - AWS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCOUNT_ID=000000000000
      - ENVIRONMENT=nonlive
      - OPENSEARCH_HOST=http://host.docker.internal:9200
      - OPENSEARCH_INDEX_ID=logs
      - OPENSEARCH_DEFAULT_VIEW_ID=default
      - ORDER_TABLE_NAME=billing.Order
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - localstack
      - opensearch
      - mcp-server-sse
    volumes:
      - ./ops-agent-backend/.env:/app/.env
      - ./ops-agent-backend/dlqs.json:/app/dlqs.json
    networks:
      - ops-network

  ops-ui:
    build:
      context: ./ops-ui
      args:
        - REACT_APP_API_BASE_URL=http://localhost:3002
        - REACT_APP_MCP_AGENT_URL=http://localhost:3001/sse
    ports:
      - "3000:80"
    depends_on:
      - mcp-api-server
      - mcp-server-sse
    networks:
      - ops-network

volumes:
  opensearch-data:

networks:
  ops-network:
    driver: bridge 